services:
  chat:
    image: chat-prod-801:${TAG}
    build:
      context: ../..
      dockerfile: deploy/dockerfiles/Dockerfile-chat
      args:
        BUILD_ENV: prod-801
        TAG: ${TAG}
    depends_on:
      chromadb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      RUNTIME_ENV: prod-801
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      HUGGING_FACE_HUB_TOKEN_FILE: /run/secrets/hf_token
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      A2RCHI_SSL_CERTIFICATE_FILE: /run/secrets/a2rchi_ssl_certicate
      A2RCHI_SSL_CERTIFICATE_KEY_FILE: /run/secrets/a2rchi_ssl_certicate_key
      MIT_CLIENT_ID_FILE: /run/secrets/mit_client_id
      MIT_CLIENT_SECRET_FILE: /run/secrets/mit_client_secret
      GOOGLE_CLIENT_ID_FILE: /run/secrets/google_client_id
      GOOGLE_CLIENT_SECRET_FILE: /run/secrets/google_client_secret
      FLASK_APP_SECRET_KEY_FILE: /run/secrets/flask_app_secret_key
    secrets:
      - openai_api_key
      - hf_token
      - pg_password
      - a2rchi_ssl_certicate
      - a2rchi_ssl_certicate_key
      - mit_client_id
      - mit_client_secret
      - google_client_id
      - google_client_secret
      - flask_app_secret_key
    volumes:
      - a2rchi-prod-801-data:/root/data/
    logging:
      options:
        max-size: 10m
    ports:
      - 7683:7861  # host:container
    restart: always

  uploader:
    image: uploader-prod-801:${TAG}
    build:
      context: ../..
      dockerfile: deploy/dockerfiles/Dockerfile-uploader
      args:
        TAG: ${TAG}
    depends_on:
      chromadb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      RUNTIME_ENV: prod-801
      FLASK_UPLOADER_APP_SECRET_KEY_FILE: /run/secrets/flask_uploader_app_secret_key
      UPLOADER_SALT_FILE: /run/secrets/uploader_salt
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      HUGGING_FACE_HUB_TOKEN_FILE: /run/secrets/hf_token
    secrets:
      - flask_uploader_app_secret_key
      - uploader_salt
      - openai_api_key
      - hf_token
    ports:
      - 5004:5001  # host:container
    volumes:
      - a2rchi-prod-801-data:/root/data/
      - /home/tier3/a2rchi/801-content/:/root/data/801-content/
    logging:
      options:
        max-size: 10m
    restart: always

  chromadb:
    image: chromadb-prod-801:${TAG}
    build:
      context: ../..
      dockerfile: deploy/dockerfiles/Dockerfile-chroma
    environment:
      RUNTIME_ENV: prod-801
      # ALLOW_RESET: True #Allow to request client to reset vstore. Functionality not currently used but keep for future debugging
    ports:
      - 8003:8000  # host:container
    volumes:
      - a2rchi-prod-801-data:/chroma/chroma/
    logging:
      options:
        max-size: 10m
    restart: always
    # healthcheck originates from inside container; so use container port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/v1/heartbeat"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s

  postgres:
    image: postgres:16
    environment:
      RUNTIME_ENV: prod-801
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_USER: a2rchi
      POSTGRES_DB: a2rchi-db
    secrets:
      - pg_password
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
      - a2rchi-prod-801-pg-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U a2rchi -d a2rchi-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana-prod-801:${TAG}
    build:
      context: ../..
      dockerfile: deploy/dockerfiles/Dockerfile-grafana
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3002:3000  # host:container
    volumes:
      - a2rchi-prod-801-grafana-data:/var/lib/grafana
      - ../grafana/a2rchi-default-dashboard.json:/var/lib/grafana/dashboards/a2rchi-default-dashboard.json
    logging:
      options:
        max-size: 10m
    restart: always

volumes:
  a2rchi-prod-801-data:
    external: true
  a2rchi-prod-801-pg-data:
    external: true
  a2rchi-prod-801-grafana-data:
    external: true

secrets:
  flask_uploader_app_secret_key:
    file: secrets/flask_uploader_app_secret_key.txt
  uploader_salt:
    file: secrets/uploader_salt.txt
  openai_api_key:
    file: secrets/openai_api_key.txt
  hf_token:
    file: secrets/hf_token.txt
  pg_password:
    file: secrets/pg_password.txt
  a2rchi_ssl_certicate:
    file: secrets/a2rchi_ssl_certificate.txt
  a2rchi_ssl_certicate_key:
    file: secrets/a2rchi_ssl_certificate_key.txt
  mit_client_id:
    file: secrets/mit_client_id.txt
  mit_client_secret:
    file: secrets/mit_client_secret.txt
  google_client_id:
    file: secrets/google_client_id.txt
  google_client_secret:
    file: secrets/google_client_secret.txt
