services:
  chat:
    image: chat:latest
    build:
      context: ../..
      dockerfile: deploy/dockerfiles/Dockerfile-chat
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      RUNTIME_ENV: dev
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      HUGGING_FACE_HUB_TOKEN_FILE: /run/secrets/hf_token
      A2RCHI_SSL_CERTIFICATE_FILE: /run/secrets/a2rchi_ssl_certicate
      A2RCHI_SSL_CERTIFICATE_KEY_FILE: /run/secrets/a2rchi_ssl_certicate_key
      MIT_CLIENT_ID_FILE: /run/secrets/mit_client_id
      MIT_CLIENT_SECRET_FILE: /run/secrets/mit_client_secret
      GOOGLE_CLIENT_ID_FILE: /run/secrets/google_client_id
      GOOGLE_CLIENT_SECRET_FILE: /run/secrets/google_client_secret
      FLASK_APP_SECRET_KEY_FILE: /run/secrets/flask_app_secret_key
    secrets:
      - openai_api_key
      - hf_token
      - a2rchi_ssl_certicate
      - a2rchi_ssl_certicate_key
      - mit_client_id
      - mit_client_secret
      - google_client_id
      - google_client_secret
      - flask_app_secret_key
    volumes:
      - a2rchi-data:/root/data/
    logging:
      options:
        max-size: 10m
    ports:
      - 7861:7861  # host:container
    restart: always

  chromadb:
    image: chromadb:latest
    build:
      context: ../..
      dockerfile: deploy/dockerfiles/Dockerfile-chroma
    environment:
      RUNTIME_ENV: dev
    ports:
      - 8000:8000  # host:container
    volumes:
      - a2rchi-data:/chroma/chroma/
    logging:
      options:
        max-size: 10m
    restart: always
    # healthcheck originates from inside container; so use container port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/api/v1/heartbeat"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s

volumes:
  a2rchi-data:
    external: true

secrets:
  openai_api_key:
    file: secrets/openai_api_key.txt
  hf_token:
    file: secrets/hf_token.txt
  a2rchi_ssl_certicate:
    file: secrets/a2rchi_ssl_certificate.txt
  a2rchi_ssl_certicate_key:
    file: secrets/a2rchi_ssl_certificate_key.txt
  mit_client_id:
    file: secrets/mit_client_id.txt
  mit_client_secret:
    file: secrets/mit_client_secret.txt
  google_client_id:
    file: secrets/google_client_id.txt
  google_client_secret:
    file: secrets/google_client_secret.txt
